export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const INVENTORY_ROUTE = '/inventory'
export const CHARACTER_ROUTE = '/character'
export const RATING_ROUTE = '/rating'
export const AUTH_ROUTE = '/auth'
export const PREPARE_ROUTE = '/prepare'
export const REACT_APP_API_URL = "http://localhost:3000"
export const SERVER_APP_API_URL = "https://afb2ltd94zwl.share.zrok.io" //"http://localhost:7000"