const classDataToDict = (classData) => {
    const dict = {};
    Object.keys(classData).forEach(key => {
      dict[key] = classData[key];
    });
    return dict;
  };

export default classDataToDict;

export const dict_translator = {
  "sign_affected": "Влияет на",
  "rating_snow": "Снежков",
  "type": "Тип",
  "weapon_damage": "Урон",
  "buff_ally": "Поддержка",
  "text": "Описание",
  "weapon_damage_type": "Тип урона",
  "attack_cost": "Стоимость атаки",
  "attack_range": "Дальность атаки",
  "value": "Цена",
  "weight": "Вес",
  "attacks": "Атаки",
  "max_charges": "Заряды",
  "is_equippable": "Можно надеть",
  "skill": "Навык",
  "enchant_damage": "Усиление урона",
  "enchant_damage_type": "Вид доб. урона",
  "crit_chance": "Шанс крит. удара",
  "2handed": "Двуручный",
  "add_damage_multiplicator": "Мульт. доб. урона",
  "defence": "Класс защиты",
  "piercing_deduction": "Вычет колющего",
  "bludge_deduction": "Вычет дробящего",
  "slashing_deduction": "Вычет рубящего",
  "fire_deduction": "Вычет огненного",
  "electric_deduction": "Вычет молнией",
  "ice_deduction": "Вычет ледяного",
  "sound_deduction": "Вычет звукового",
  "wind_deduction": "Вычет воздушного",
  "mind_deduction": "Вычет мыслью",
  "light_deduction": "Вычет светом",
  "dark_deduction": "Вычет тьмой",
  "life_deduction": "Вычет жизнью",
  "death_deduction": "Вычет смертью",
  "piercing": "Колющий",
  "bludge": "Дробящий",
  "slashing": "Рубящий",
  "fire": "Огненный",
  "electric": "Электрический",
  "ice": "Ледяной",
  "sound": "Звуковой",
  "wind": "Воздушный",
  "mind": "Урон мысли",
  "sheak_check": "Мод. скрытности",
  "supplies_on_cook": "Припасы при готовке",
  "healing": "Лечение",
  "food": "Еда",
  "supplies": "Расходник",
  "potions": "Зелье",
  "breast_armor": "Доспех",
  "left_hand": "Левая рука",
  "right_hand": "Оружие",
  "head": "Шлем",
  "cloak": "Плащ",
  "ring_1": "Кольцо1",
  "ring_2": "Кольцо2",
  "ring_3": "Кольцо3",
  "ring_4": "Кольцо4",
  "ring_5": "Кольцо5",
  "gloves": "Перчатки",
  "necklace": "Амулет",
  "leg_armor": "Поножи",
  "boots": "Обувь",
  "belt": "Пояс",
  False: "Нет",
  True: "Да",
  "true": "Да",
  "false": "Нет",
  "knifes": "Кинжалы",
  "swords": "Мечи",
  "axes": "Топоры",
  "hammers": "Молоты",
  "spears": "Копья",
  "staffs": "Посохи",
  "bows": "Луки",
  "crossbows": "Арбалеты",
  "throwing weapon": "Метательное",
  "shield": "Щиты",
  "available_signs": "Доступные к изучению знаки",
  "prepared_magic": "Подготовленные заклинания",
  "magic_attack": "Маг. атака",
  "magic_damage": "Маг. урон",
  "pray_attack": "Атака духа",
  "pray_damage": "Урон духа",
  "sign_fire": "Огонь",
  "sign_ice": "Лёд",
  "sign_electric": "Электричество",
  "sign_wind": "Ветер",
  "sign_stone": "Камень",
  "sign_power": "Власть",
  "sign_sound": "Звук",
  "sign_light": "Свет",
  "sign_dark": "Тьма",
  "sign_life": "Жизнь",
  "sign_death": "Смерть",
  "sign_touch": "Длань",
  "sign_distant": "Сгусток",
  "sign_ray": "Поток",
  "sign_weapon_enchant": "Улучшение оружия",
  "sign_armor_enchant": "Сфера",
  "sign_dash": "Рывок",
  "dash": "Рывок",
  "sign_magic_effect": "Аугментация Мощи",
  "sign_magic_accuracy": "Аугментация Точности",
  "sign_magic_range": "Аугментация Дальности",
  "scroll": "Свиток",
  "reagent": "Реагент",
  "junk": "Хлам",
  "sneak_check": "Мод. проверок скрытности",
  "ranged_weapon": "Оружие дальнего боя",
  "ammo": "Боеприпас",
  "sign": "Знак",
  "reload_cost": "Стоимость перезарядки",
  "ready_to_fire": "Заряжен",
  "name": "Имя",
  "damage": "Урон",
  "arm_armor": "Наручи",
  "ring": "Кольцо",
  "current_action_points": "Текущие ОД",
  "parry": "Парирование",
  "consumable_items": "Расходуемые предметы",
  "current_health": "Текущее здоровье",
  "No": "Нет",
  "Fighter": "Воин",
  "required_class": "Требуемый класс",
  "agility": "Ловкость",
  "strength": "Сила",
  "perception": "Восприятие",
  "constitution": "Выносливость",
  "intelligence": "Интеллект",
  "wisdom": "Мудрость",
  "charisma": "Харизма",
  "luck": "Удача",
  "initiative": "Инициатива",
  "rage": "Ярость",
  "bloodlust": "Кровожадность",
  "gender": "Пол",
  "m": "Мужской",
  "f": "Женский",
  "n": "Средний",
  "number": "Число",
  "plural": "Множественное",
  "singular": "Единственное",
  "rating_experience": "Опыта",
  "rating_level": "Уровней",
  "rating_locations": "Локаций",
  "rating_skills": "Навыков",
  "wrestling": "Борьба",
  "throwing_weapon": "Метательное",
  "implant": "Протез",
  "medicine": "Медицина",
  "injury_hand": "Травма руки",
  "injury_leg": "Травма ноги",
  "passive": "Пассивное",
  "buff": "Усиление",
  "effects": "Эффекты",
  "Attack_ability": "Атакующее",
  "charges": "Заряды",
  "skill_requirement": "Требования навыка",
  "damage_multiplicator": "Увеличение урона",
  "targets": "Цели",
  "active_magic_slots": "Осталось заклинаний",
  "buff_type": "Тип усиления",
  "weapon": "Оружия",
  "distance": "Расстояние",
  "cost": "Стоимость ОД",
  "magic_type": "Тип магии",
  "Mage": "Маг",
  "Priest": "Жрец",
  "damage_type": "Тип урона",
  "life": "Жизнь",
  "death": "Смерть",
  "associated_skills": "Влияющие навыки",
  "power": "Власть",
  "attack": "Атакующее",
  "secondary_weapon": "Запасное оружие",
  "level": "Уровень",
  "move_cost": "Стоимость перемещения",
  "prefix_damage_type": "Тип урона зачарования",
  "prefix_damage": "Урон зачарования оружия",
  "Fargos-downtown-instructor": "У инструктора",
  "current_weight": "🏋",
  "experience": "Опыт",
  "money": "Монеты",
  "melee_attack": "Атака в ближнем бою",
  "melee_damage": "Урон в ближнем бою",
  "range_attack": "Атака в дальнем бою",
  "range_damage": "Урон в дальнем бою",
  "action_points": "🏃",
  "free_attribute_points": "Свободные очки атрибутов",
  "Race": "Раса",
  "Character_class": "Класс",
  "magic_resist": "Маг. сопротивление",
  "discount": "Скидка",
  "points_per_level": "Очки навыков за уровень",
  "free_skill_points": "Свободные очки навыков",
  "free_talent_points": "Свободные очки талантов",
  "max_party_size": "Максимальный размер группы",
  "move_OP": "Доп. очки передвижения",
  "location": "Локация",
  "duration": "Длительность эффекта",
  "end_time": "Окончание эффекта",
  "Yes": "Да",
  "goods": "Товары",
  "twohanded": "Двуручное",
  "Dungeon_Stone": "🏔Кристаллические горы",
  "Dungeon_Ice": "❄Студёный престол",
  "Dungeon_Electricity": "⚡Грозовой перевал",
  "Dungeon_Light": "🌝Цитадель света",
  "Dungeon_Death": "💀Некрополь",
  "Dungeon_Fire": "🔥Огненные озёра",
  "Dungeon_Dark": "🌚Цитадель тьмы",
  "Dungeon_Life": "🌿Сердце Цветения",
  "Dungeon_Wind": "💨Штормовой грот",
  "Dungeon_Sound": "🌀Пещеры эха",
  "Dungeon_Power": "👑Чертог власти",
  "Tavern": "🍺Таверна",
  "Canalisation_rat_king": "⛓️Плен у крыс",
  "Castle_Stone": "Замок Камня",
  "Castle_Ice": "Замок Льда",
  "Castle_Electricity": "Замок Молнии",
  "Castle_Light": "Замок Света",
  "Castle_Death": "Замок Смерти",
  "Castle_Fire": "Замок Огня",
  "Castle_Dark": "Замок Тьмы",
  "Castle_Life": "Замок Жизни",
  "Castle_Wind": "Замок Ветра",
  "Castle_Sound": "Замок Звука",
  "Castle_Power": "Замок Власти",
  "push": "Отталкивание",
  "Additional damage": "Доп. урон в 1 ходу",
  "suffix": "Суффикс",
  "turns": "Ходы",
  "undefined": "свойства не раскрыты",
  "Fargos-downtown": "Нижний город Фаргоса",
  "Fargos-uptown": "Верхний город Фаргоса",
  "West_wildlands": "Западные Дикие Земли",
  "monet": "Монет",
  "bleed": "Кровотечение",
  "poison": "Отравление",
  "power_deduction": "Вычет Власти",
  "light": "Световой",
  "dark": "Тёмный",
  "stone": "Дробящий",
  "prefix_skill": "Знак зачарования",
  "prefix": "Зачарование",
  "ressurect": "Воскрешение",
  "regeneration": "Регенерация",
  "Wild_lands_coast": "🏝️Побережье",
  "Wild_lands_steppe": "🏜️Степь",
  "Wild_lands_forest": "🌲Лес",
  "Wild_lands_mountains": "⛰️Горы",
  "corrupted": "Проклят",
  "vampirism": "Вампиризм",
  "range": "Дальность",
  "summon": "Призыв",
  "ability": "Умение",
  "enchant_skill1": "Влияющий навык",
  "enchant_skill2": "Влияющий навык",
  "check": "Проверка атрибута",
  "attribute": "Характеристика",
  "difficulty": "Сложность проверки",
  "failure": "Провал",
  "Fargos-downtown-canalisation": "🕳Канализация",
  "Fargos-downtown-gardens": "🌷Сады Фаргоса",
  "Fargos-uptown-tavern": "🍷Таверна Верхнего города",
  "Fargos-downtown-tavern": "🍺Таверна Нижнего города",
  "Fargos-downtown-market": "💰Рынок Нижнего города",
  "Fargos-downtown-towngates": "⛩️Городские ворота Фаргоса",
  "Fargos-downtown-slums": "⚓Портовый район Нижнего города",
  "Fargos-downtown-artisans": "🔨Ремесленный район Нижнего города",
  "Archery_place": "🏹Стрельбище",
  "rating_levels": "Уровней",
  "aura": "Сфера",
  "is_alive": "Жив",
  "Canalisation": "🕳Канализация",
  "level_scale": "Масштабируемый предмет",
  "improve": "Аугментации",
  "daleon": "Далеон",
  "magic_slots": "Применения заклинаний",
  "current_defence": "Класс защиты",
  "additional_attack": "Доп.ы точность",
  "eon_curse": "Проклятие Эона",
  "additional_damage": "Доп. урон",
  "reset_character": "Обновление персонажа",
  "Necropolis_necromancer": "Логово некроманта",
  "scrolls": "Свитки",
  "description": "Описание",
}


export const abilities_descriptions = {
  "Призыв куклы": "Усиление атаки, призывает куклу колдуна после применения, 1 заряд до отдыха",
  "Волна звука": "Усиление атаки, бьющее по 2 целям и наносящее дополнительный урон звуком, 2 заряда до отдыха",
  "Шаровая молния": "Усиление атаки, бьющее по 2 целям и наносящее дополнительный урон электричеством, 2 заряда до отдыха",
  "Морозное дыхание": "Усиление атаки, бьющее по 2 целям и наносящее дополнительный урон холодом, 2 заряда до отдыха",
  "Сопротивление стихиям": "Умение усиления, увеличивающее сопротивление стихиям, стоимость применения 2 ОД, 1 заряд до отдыха",
  "Призыв тени": "Усиление атаки, призывает тень после применения, 3 заряда до отдыха",
  "Всплеск действий": "Умение усиления, увеличивающее запас очков действий на 10, стоимость применения 2 ОД, 1 заряд до отдыха",
  "Призыв нежити": "Усиление атаки, призывает нежить после применения, 1 заряд до отдыха",
  "Порыв ветра": "Усиление атаки, отталкивает противника на 6 клеток, 3 заряда до отдыха",
  "Удар вампира": "Усиление атаки, восстанавливающая атакующему половину нанесённого урона, 3 заряда до отдыха",
  "Призыв существа": "Усиление атаки, призывает случайное существо после применения, 1 заряд до отдыха",
  "Скорбь": "Усиление атаки, снижающее ОД противника на 10 при провале броска харизмы со сложностью 20, 1 заряд до отдыха",
  "Призыв дендроида": "Усиление атаки, призывает дендроидп после применения, 1 заряд до отдыха",
  "Поиск жертвы": "Увеличивает шанс на нахождение искателя приключений в 4 раза.\nЕсли вы побеждаете противника с таким же амулетом - вы забираете у него случайный предмет"
}

export const attributes_dict = {"perception": "Восприятие", "strength": "Сила", "agility": "Ловкость",
"constitution": "Выносливость", "intelligence": "Интеллект", "charisma": "Харизма",
"wisdom": "Мудрость", "luck": "Удача"}

export const RESOURCE_CODES = {
    "112": { name: "Железная руда", icon: "fa-mountain" },
    "114": { name: "Бревно", icon: "fa-tree" },
    "115": { name: "Мешок угля", icon: "fa-coal" },
    "116": { name: "Песчаник", icon: "fa-hill-rockslide" },
    "117": { name: "Мешок песка", icon: "fa-filter" },
    "118": { name: "Стекло", icon: "fa-wine-glass" },
    "119": { name: "Доска", icon: "fa-border-all" },
    "120": { name: "Сталь", icon: "fa-industry" },
    "121": { name: "Каменный блок", icon: "fa-cube" },
    "essence": { name: "Воплощение", icon: "fa-heart" },
    "leather_t1": { name: "Кожа Т1", icon: "fa-leather" },
    "leather_t2": { name: "Кожа Т2", icon: "fa-leather" },
    "leather_t3": { name: "Кожа Т3", icon: "fa-leather" },
};

export const SETTLEMENT_TYPES = {
    "death": "Смерть",
    "fire": "Огонь",
    "water": "Вода",
    "earth": "Земля",
    "air": "Воздух",
    "lighting": "Молния"
};

export const BUILDING_ACTIONS = {
    "build": "Построить/Улучшить",
    "repair": "Ремонтировать",
    "hire": "Нанять юнитов",
    "ritual": "Провести ритуал",
    "storage": "Управление складом"
};